import { test,expect } from '@playwright/test';
test('gatilhos: simulação isolada e reconhecimento de um sinal da sessão',async({page})=>{
 await page.goto('/');
 await page.getByRole('button',{name:'Explorar gatilhos'}).click();
 await expect(page.getByRole('heading',{name:'Quem ajudou também aparece'})).toBeVisible();
 const before=(await (await page.request.get('/api/state')).json()).state;
 await page.getByRole('button',{name:'Concluir com ajuda de Lara'}).click();
 const result=page.locator('.simulation-result');
 await expect(result).toContainText('3 SINAIS NO EXEMPLO');
 await expect(result.locator('.highlighted')).toContainText('Lara Pontes');
 await expect(result.locator('.highlighted')).toContainText('Ajudou um colega');
 const after=(await (await page.request.get('/api/state')).json()).state;
 expect(after).toEqual(before);
 await page.getByRole('button',{name:'Complexidade Entrega de alta complexidade'}).click();
 await page.getByRole('button',{name:'Concluir migração'}).click();
 await expect(result.locator('.highlighted')).toContainText('Tiago Moraes');
 await page.getByLabel('Filtrar por gatilho').selectOption('ausencia');
 await expect(page.locator('.signal-card')).toHaveCount(2);
 const sofia=page.locator('.signal-card').filter({hasText:'Sofia Andrade'});
 await sofia.getByRole('button',{name:'Reconhecer contribuição'}).click();
 await expect(page.getByRole('heading',{name:'Reconhecer Sofia'})).toBeVisible();
 await expect(page.locator('.compose')).toContainText('97 dias');
});

test('gatilhos em celular: exemplos e sinais cabem na tela',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');
 await page.getByRole('button',{name:'Gatilhos',exact:true}).click();
 await page.getByRole('button',{name:'Concluir com ajuda de Lara'}).click();
 await expect(page.locator('.simulation-result')).toContainText('Lara Pontes');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'test-results/gatilhos-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:'test-results/gatilhos-desktop.png',fullPage:true});
});

test('fluxo completo: atividade, ajuda, reconhecimento e persistência',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.getByRole('heading',{name:'Quadro do time de desenvolvimento'})).toBeVisible();
 const card=page.locator('article.card').filter({hasText:'Filtro de período na listagem de clientes'});
 await card.getByRole('button',{name:'Avançar'}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByRole('dialog').getByRole('button',{name:'Lara Pontes'}).click();
 await page.getByRole('button',{name:'Marcar como pronta'}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await expect(card.getByText('Ajuda de Lara Pontes')).toBeVisible();
 await expect(page.getByRole('region',{name:'Novos sinais gerados'})).toContainText('3 novos sinais gerados');
 await expect(page.getByRole('region',{name:'Novos sinais gerados'})).toContainText('Ajudou um colega');
 await card.getByRole('button',{name:'Marcar como referência'}).click();
 await expect(card.getByText('implementação de referência')).toBeVisible();
 await page.getByRole('button',{name:'Reconhecer',exact:false}).first().click();
 await page.getByRole('button',{name:'Escrever reconhecimento'}).first().click();
 await page.getByLabel('O que essa contribuição significou para o time?').fill('A revisão cuidadosa evitou erros na entrega. Obrigada pelo apoio!');
 await page.getByRole('button',{name:'Salvar reconhecimento'}).click();
 await expect(page.getByRole('status')).toHaveText('Alteração salva.');
 await page.getByRole('button',{name:'Mural',exact:true}).click();
 await expect(page.getByText('A revisão cuidadosa evitou erros na entrega. Obrigada pelo apoio!',{exact:true})).toBeVisible();
 await page.reload();
 await page.getByRole('button',{name:'Mural',exact:true}).click();
 await expect(page.getByText('A revisão cuidadosa evitou erros na entrega. Obrigada pelo apoio!',{exact:true})).toBeVisible();
 await page.screenshot({path:'test-results/mural-desktop.png',fullPage:true});
 expect(errors).toEqual([]);
});
test('sessões isoladas, validação de origem e ausência de tokens na resposta',async({browser})=>{
 const a=await browser.newContext(),b=await browser.newContext();
 const first=await a.request.get('/api/state');const second=await b.request.get('/api/state');
 expect((await second.json()).state.feed).toEqual([]);
 const headers={origin:'http://localhost:3000'};
 const action=await a.request.post('/api/actions',{headers,data:{action:'recognize',person:'lara',text:'Registro exclusivo da sessão A',visibility:'privado',group:'area'}});
 expect(action.ok()).toBeTruthy();
 expect((await (await b.request.get('/api/state')).json()).state.feed).toEqual([]);
 const forbidden=await a.request.post('/api/actions',{headers:{origin:'https://evil.example'},data:{action:'dismiss',person:'lara'}});
 expect(forbidden.status()).toBe(400);
 const serialized=await first.text();expect(serialized).not.toContain('access_token');expect(serialized).not.toContain('refresh_token');
 await a.close();await b.close();
});
test('mobile: navegação, busca e estado da integração',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');
 await expect(page.getByRole('heading',{name:'Quadro do time de desenvolvimento'})).toBeVisible();
 await page.getByPlaceholder('Título ou responsável').fill('gateway');
 await expect(page.locator('article.card')).toHaveCount(1);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'test-results/quadro-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Integração Jira',exact:true}).click();
 await expect(page.getByRole('link',{name:'Conectar Jira',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Alternar tema'}).click();
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await page.screenshot({path:'test-results/integracao-mobile.png',fullPage:true});
});
