import { connection, saveConnection, type Connection } from './store';
import type { State,Card } from './model';
import { appUrl } from './http';
export function config(){const client_id=process.env.ATLASSIAN_CLIENT_ID;const client_secret=process.env.ATLASSIAN_CLIENT_SECRET;if(!client_id||!client_secret||!/^[a-fA-F0-9]{64}$/.test(process.env.TOKEN_ENCRYPTION_KEY||''))throw new Error('A integração ainda não foi configurada. Preencha as variáveis da Atlassian no servidor.');return {client_id,client_secret,redirect_uri:`${appUrl()}/api/jira/callback`};}
export async function exchange(body:Record<string,string>){const r=await fetch('https://auth.atlassian.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...config(),...body}),signal:AbortSignal.timeout(20000),cache:'no-store'});if(!r.ok)throw new Error('A autorização do Jira expirou ou não pôde ser validada. Conecte novamente.');return r.json() as Promise<{access_token:string;refresh_token?:string;expires_in:number}>;}
const refreshes=new Map<string,Promise<Connection>>();
export async function authorized(id:string):Promise<Connection>{const c=connection(id);if(!c)throw new Error('Conecte o Jira primeiro.');if(c.expiresAt>Date.now()+60000)return c;if(!c.refresh_token)throw new Error('Conecte o Jira novamente.');let pending=refreshes.get(id);if(!pending){pending=(async()=>{const token=await exchange({grant_type:'refresh_token',refresh_token:c.refresh_token!});const next={...c,...token,expiresAt:Date.now()+token.expires_in*1000};saveConnection(id,next);return next;})().finally(()=>refreshes.delete(id));refreshes.set(id,pending);}return pending;}
export async function jira(id:string,site:string,path:string,body?:unknown){const c=await authorized(id);if(!c.sites.some(s=>s.id===site))throw new Error('Site não autorizado.');const r=await fetch(`https://api.atlassian.com/ex/jira/${encodeURIComponent(site)}/rest/api/3/${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${c.access_token}`,Accept:'application/json','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(r.status===429?'Limite de consultas do Jira atingido. Tente novamente em alguns instantes.':`Não foi possível consultar o Jira (${r.status}). Verifique o acesso ao projeto.`);return r.json();}
export type Issue={id:string;key:string;fields:{summary:string;status:{id:string;name:string;statusCategory:{key:string}};assignee:null|{accountId:string;displayName:string};issuetype:{id:string;name:string};priority?:{name:string};duedate?:string}};
export function importIssues(previous:State,issues:Issue[],statuses:{id:string;name:string;category:string}[],site:{id:string;url:string},project:string):State{
 const same=previous.source==='jira'&&previous.project===`${site.id}:${project}`;
 const result:State={source:'jira',people:{},types:{},stages:statuses.map(s=>({id:s.id,n:s.name,d:s.category==='done'?'concluído':'etapa do Jira'})),cards:[],signals:[],feed:same?previous.feed:[],dismissed:same?previous.dismissed:0,project:`${site.id}:${project}`,syncedAt:new Date().toISOString()};
 for(const issue of issues){const f=issue.fields;const person=f.assignee?.accountId||'';if(person){const name=f.assignee!.displayName;result.people[person]=same&&previous.people[person]?previous.people[person]:{nome:name,papel:'Colaborador no Jira',ini:name.split(' ').map(n=>n[0]).slice(0,2).join(''),dias:null,ritmo:0,entregas:0};}result.types[f.issuetype.id]={nome:f.issuetype.name,compl:'unknown'};let stage=result.stages.findIndex(s=>s.id===f.status.id);if(stage===-1){stage=result.stages.length;result.stages.push({id:f.status.id,n:f.status.name,d:'etapa do Jira'});}const old=same?previous.cards.find(c=>c.id===issue.id):undefined;const card:Card={id:issue.id,t:f.summary,tipo:f.issuetype.id,dono:person,fase:stage,retrab:0,aval:null,ajuda:[],modelo:old?.modelo||false,priority:f.priority?.name,due:f.duedate,url:`${site.url}/browse/${encodeURIComponent(issue.key)}`,done:f.status.statusCategory.key==='done'};result.cards.push(card);if(person&&card.done&&old&&!old.done)result.signals.push({id:`done:${issue.id}`,pessoa:person,tipo:'conclusao',frase:`Concluiu “${card.t}” desde a última sincronização.`});}
 if(same){result.signals=[...previous.signals.filter(s=>result.people[s.pessoa]),...result.signals.filter(s=>!previous.signals.some(p=>p.id===s.id))];result.feed=result.feed.filter(f=>result.people[f.para]);}return result;
}
